### PR TITLE
Added #of alias for Dry::Types::Array#member

### PR DESCRIPTION
**Pull request by maliqq**

### CODE REVIEW

**Comment by solnic** [comment]
No strong feelings about this. WDYT @timriley?

**Comment by flash-gordon** [comment]
I think this is fine :)

**Comment by timriley** [comment]
I missed the notification back on 12th of May, but yeah, this seems innocuous.

My only question would be whether `#of` should be the official API, and `#member` deprecated? I don't really see much point in keeping _both_ methods around.

**Comment by flash-gordon** [comment]
Yeah, from now on `#of` is my personal preference, @solnic wdyt?

**Comment by solnic** [comment]
It's OK

**Pull request merged**
