### PR TITLE
Rename Types::Form to Types::Params

### LINKED ISSUE #219: Rename `Types::Form` => `Types::Params`

### PR DESCRIPTION
**Pull request by ndrluis**
Closes #219

### CODE REVIEW

**Comment by GustavoCaso** [comment]
@solnic can we merge this one?

**Comment by davydovanton** [comment]
@GustavoCaso WDYT about deprecation warning? I think it will be really good for developers to prepare for the new changes 🤔

**Comment by solnic** [comment]
We should do the same as with `Int => Integer`. See https://github.com/dry-rb/dry-types/blob/master/lib/dry/types/compat/int.rb

**Comment by GustavoCaso** [comment]
@solnic I'm happy to rebase master and add the deprecation warning.

**Pull request merged**
