### PR TITLE
Reduce memory allocation with simple micro optimizations

### PR DESCRIPTION
**Pull request by davydovanton**
Hello,
I reduced some allocations. [As you can see][results] this changes improve benchmark about 25%.

[results]: https://gist.github.com/davydovanton/40ddc298496839edc3b11c2adc0086b1

### CODE REVIEW

**Comment by backus** [comment]
Could you also share the code that produced the benchmark?

**Comment by davydovanton** [comment]
@backus it was scheme benchmark from dry-types repository :)

**Comment by backus** [comment]
Ah ok. What about the allocation stuff?

**Comment by solnic** [comment]
Aah nice. `each_with_object` is known to be slower

**Comment by davydovanton** [comment]
@backus I used memory profiler (https://github.com/SamSaffron/memory_profiler) and call benchmark code in profiler block.

@solnic thanks for merge 🍻

**Comment by solnic** [comment]
FYI this has been released already in v0.9.2. I noticed an improvement in perf in dry-validation too <3

**Pull request merged**
